<?php
return [

    'AED' => [
        'name'                => 'UAE Dirham',
        'code'                => 784,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'د.إ',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'AFN' => [
        'name'                => 'Afghani',
        'code'                => 971,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '؋',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'ALL' => [
        'name'                => 'Lek',
        'code'                => 8,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'L',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'AMD' => [
        'name'                => 'Armenian Dram',
        'code'                => 51,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'դր.',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'ANG' => [
        'name'                => 'Netherlands Antillean Guilder',
        'code'                => 532,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'ƒ',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'AOA' => [
        'name'                => 'Kwanza',
        'code'                => 973,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Kz',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'ARS' => [
        'name'                => 'Argentine Peso',
        'code'                => 32,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'AUD' => [
        'name'                => 'Australian Dollar',
        'code'                => 36,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ' ',
    ],

    'AWG' => [
        'name'                => 'Aruban Florin',
        'code'                => 533,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'ƒ',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'AZN' => [
        'name'                => 'Azerbaijanian Manat',
        'code'                => 944,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₼',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'BAM' => [
        'name'                => 'Convertible Mark',
        'code'                => 977,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'КМ',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'BBD' => [
        'name'                => 'Barbados Dollar',
        'code'                => 52,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'BDT' => [
        'name'                => 'Taka',
        'code'                => 50,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '৳',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'BGN' => [
        'name'                => 'Bulgarian Lev',
        'code'                => 975,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'лв',
        'symbol_first'        => false,
        'decimal_mark'        => ',',
        'thousands_separator' => ' ',
    ],

    'BHD' => [
        'name'                => 'Bahraini Dinar',
        'code'                => 48,
        'minorUnit'           => 3,
        'subunit'             => 1000,
        'symbol'              => 'ب.د',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'BIF' => [
        'name'                => 'Burundi Franc',
        'code'                => 108,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'Fr',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'BMD' => [
        'name'                => 'Bermudian Dollar',
        'code'                => 60,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'BND' => [
        'name'                => 'Brunei Dollar',
        'code'                => 96,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'BOB' => [
        'name'                => 'Boliviano',
        'code'                => 68,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Bs.',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'BOV' => [
        'name'                => 'Mvdol',
        'code'                => 984,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Bs.',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'BRL' => [
        'name'                => 'Brazilian Real',
        'code'                => 986,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'R$',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'BSD' => [
        'name'                => 'Bahamian Dollar',
        'code'                => 44,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'BTN' => [
        'name'                => 'Ngultrum',
        'code'                => 64,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Nu.',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'BWP' => [
        'name'                => 'Pula',
        'code'                => 72,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'P',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'BYN' => [
        'name'                => 'Belarussian Ruble',
        'code'                => 974,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'Br',
        'symbol_first'        => false,
        'decimal_mark'        => ',',
        'thousands_separator' => ' ',
    ],

    'BZD' => [
        'name'                => 'Belize Dollar',
        'code'                => 84,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'CAD' => [
        'name'                => 'Canadian Dollar',
        'code'                => 124,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'CDF' => [
        'name'                => 'Congolese Franc',
        'code'                => 976,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Fr',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'CHF' => [
        'name'                => 'Swiss Franc',
        'code'                => 756,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'CHF',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'CLF' => [
        'name'                => 'Unidades de fomento',
        'code'                => 990,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'UF',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'CLP' => [
        'name'                => 'Chilean Peso',
        'code'                => 152,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'CNY' => [
        'name'                => 'Yuan Renminbi',
        'code'                => 156,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '¥',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'COP' => [
        'name'                => 'Colombian Peso',
        'code'                => 170,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'CRC' => [
        'name'                => 'Costa Rican Colon',
        'code'                => 188,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₡',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'CUC' => [
        'name'                => 'Peso Convertible',
        'code'                => 931,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'CUP' => [
        'name'                => 'Cuban Peso',
        'code'                => 192,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'CVE' => [
        'name'                => 'Cape Verde Escudo',
        'code'                => 132,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'CZK' => [
        'name'                => 'Czech Koruna',
        'code'                => 203,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Kč',
        'symbol_first'        => false,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'DJF' => [
        'name'                => 'Djibouti Franc',
        'code'                => 262,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'Fdj',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'DKK' => [
        'name'                => 'Danish Krone',
        'code'                => 208,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'kr',
        'symbol_first'        => false,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'DOP' => [
        'name'                => 'Dominican Peso',
        'code'                => 214,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'DZD' => [
        'name'                => 'Algerian Dinar',
        'code'                => 12,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'د.ج',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'EGP' => [
        'name'                => 'Egyptian Pound',
        'code'                => 818,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'ج.م',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'ERN' => [
        'name'                => 'Nakfa',
        'code'                => 232,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Nfk',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'ETB' => [
        'name'                => 'Ethiopian Birr',
        'code'                => 230,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Br',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'EUR' => [
        'name'                => 'Euro',
        'code'                => 978,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '€',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'FJD' => [
        'name'                => 'Fiji Dollar',
        'code'                => 242,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'FKP' => [
        'name'                => 'Falkland Islands Pound',
        'code'                => 238,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '£',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'GBP' => [
        'name'                => 'Pound Sterling',
        'code'                => 826,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '£',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'GEL' => [
        'name'                => 'Lari',
        'code'                => 981,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₾',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'GHS' => [
        'name'                => 'Ghana Cedi',
        'code'                => 936,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₵',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'GIP' => [
        'name'                => 'Gibraltar Pound',
        'code'                => 292,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '£',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'GMD' => [
        'name'                => 'Dalasi',
        'code'                => 270,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'D',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'GNF' => [
        'name'                => 'Guinea Franc',
        'code'                => 324,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'Fr',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'GTQ' => [
        'name'                => 'Quetzal',
        'code'                => 320,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Q',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'GYD' => [
        'name'                => 'Guyana Dollar',
        'code'                => 328,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'HKD' => [
        'name'                => 'Hong Kong Dollar',
        'code'                => 344,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'HNL' => [
        'name'                => 'Lempira',
        'code'                => 340,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'L',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'HRK' => [
        'name'                => 'Croatian Kuna',
        'code'                => 191,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'kn',
        'symbol_first'        => false,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'HTG' => [
        'name'                => 'Gourde',
        'code'                => 332,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'G',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'HUF' => [
        'name'                => 'Forint',
        'code'                => 348,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Ft',
        'symbol_first'        => false,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'IDR' => [
        'name'                => 'Rupiah',
        'code'                => 360,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Rp',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'ILS' => [
        'name'                => 'New Israeli Sheqel',
        'code'                => 376,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₪',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'INR' => [
        'name'                => 'Indian Rupee',
        'code'                => 356,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₹',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'IQD' => [
        'name'                => 'Iraqi Dinar',
        'code'                => 368,
        'minorUnit'           => 3,
        'subunit'             => 1000,
        'symbol'              => 'ع.د',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'IRR' => [
        'name'                => 'Iranian Rial',
        'code'                => 364,
        'minorUnit'           => 0,
        'subunit'             => 100,
        'symbol'              => '﷼',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'ISK' => [
        'name'                => 'Iceland Krona',
        'code'                => 352,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'kr',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'JMD' => [
        'name'                => 'Jamaican Dollar',
        'code'                => 388,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'JOD' => [
        'name'                => 'Jordanian Dinar',
        'code'                => 400,
        'minorUnit'           => 3,
        'subunit'             => 100,
        'symbol'              => 'د.ا',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'JPY' => [
        'name'                => 'Yen',
        'code'                => 392,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => '¥',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'KES' => [
        'name'                => 'Kenyan Shilling',
        'code'                => 404,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'KSh',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'KGS' => [
        'name'                => 'Som',
        'code'                => 417,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'som',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'KHR' => [
        'name'                => 'Riel',
        'code'                => 116,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '៛',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'KMF' => [
        'name'                => 'Comoro Franc',
        'code'                => 174,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'Fr',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'KPW' => [
        'name'                => 'North Korean Won',
        'code'                => 408,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₩',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'KRW' => [
        'name'                => 'Won',
        'code'                => 410,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => '₩',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'KWD' => [
        'name'                => 'Kuwaiti Dinar',
        'code'                => 414,
        'minorUnit'           => 3,
        'subunit'             => 1000,
        'symbol'              => 'د.ك',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'KYD' => [
        'name'                => 'Cayman Islands Dollar',
        'code'                => 136,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'KZT' => [
        'name'                => 'Tenge',
        'code'                => 398,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '〒',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'LAK' => [
        'name'                => 'Kip',
        'code'                => 418,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₭',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'LBP' => [
        'name'                => 'Lebanese Pound',
        'code'                => 422,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'ل.ل',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'LKR' => [
        'name'                => 'Sri Lanka Rupee',
        'code'                => 144,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₨',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'LRD' => [
        'name'                => 'Liberian Dollar',
        'code'                => 430,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'LSL' => [
        'name'                => 'Loti',
        'code'                => 426,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'L',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'LTL' => [
        'name'                => 'Lithuanian Litas',
        'code'                => 440,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Lt',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'LVL' => [
        'name'                => 'Latvian Lats',
        'code'                => 428,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Ls',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'LYD' => [
        'name'                => 'Libyan Dinar',
        'code'                => 434,
        'minorUnit'           => 3,
        'subunit'             => 1000,
        'symbol'              => 'ل.د',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'MAD' => [
        'name'                => 'Moroccan Dirham',
        'code'                => 504,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'د.م.',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'MDL' => [
        'name'                => 'Moldovan Leu',
        'code'                => 498,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'L',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'MGA' => [
        'name'                => 'Malagasy Ariary',
        'code'                => 969,
        'minorUnit'           => 2,
        'subunit'             => 5,
        'symbol'              => 'Ar',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'MKD' => [
        'name'                => 'Denar',
        'code'                => 807,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'ден',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'MMK' => [
        'name'                => 'Kyat',
        'code'                => 104,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'K',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'MNT' => [
        'name'                => 'Tugrik',
        'code'                => 496,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₮',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'MOP' => [
        'name'                => 'Pataca',
        'code'                => 446,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'P',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'MRO' => [
        'name'                => 'Ouguiya',
        'code'                => 478,
        'minorUnit'           => 2,
        'subunit'             => 5,
        'symbol'              => 'UM',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'MUR' => [
        'name'                => 'Mauritius Rupee',
        'code'                => 480,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₨',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'MVR' => [
        'name'                => 'Rufiyaa',
        'code'                => 462,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'MVR',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'MWK' => [
        'name'                => 'Kwacha',
        'code'                => 454,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'MK',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'MXN' => [
        'name'                => 'Mexican Peso',
        'code'                => 484,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'MYR' => [
        'name'                => 'Malaysian Ringgit',
        'code'                => 458,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'RM',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'MZN' => [
        'name'                => 'Mozambique Metical',
        'code'                => 943,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'MTn',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'NAD' => [
        'name'                => 'Namibia Dollar',
        'code'                => 516,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'NGN' => [
        'name'                => 'Naira',
        'code'                => 566,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₦',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'NIO' => [
        'name'                => 'Cordoba Oro',
        'code'                => 558,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'C$',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'NOK' => [
        'name'                => 'Norwegian Krone',
        'code'                => 578,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'kr',
        'symbol_first'        => false,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'NPR' => [
        'name'                => 'Nepalese Rupee',
        'code'                => 524,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₨',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'NZD' => [
        'name'                => 'New Zealand Dollar',
        'code'                => 554,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'OMR' => [
        'name'                => 'Rial Omani',
        'code'                => 512,
        'minorUnit'           => 3,
        'subunit'             => 1000,
        'symbol'              => 'ر.ع.',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'PAB' => [
        'name'                => 'Balboa',
        'code'                => 590,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'B/.',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'PEN' => [
        'name'                => 'Sol',
        'code'                => 604,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'S/',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'PGK' => [
        'name'                => 'Kina',
        'code'                => 598,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'K',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'PHP' => [
        'name'                => 'Philippine Peso',
        'code'                => 608,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₱',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'PKR' => [
        'name'                => 'Pakistan Rupee',
        'code'                => 586,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₨',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'PLN' => [
        'name'                => 'Zloty',
        'code'                => 985,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'zł',
        'symbol_first'        => false,
        'decimal_mark'        => ',',
        'thousands_separator' => ' ',
    ],

    'PYG' => [
        'name'                => 'Guarani',
        'code'                => 600,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => '₲',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'QAR' => [
        'name'                => 'Qatari Rial',
        'code'                => 634,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'ر.ق',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'RON' => [
        'name'                => 'New Romanian Leu',
        'code'                => 946,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Lei',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'RSD' => [
        'name'                => 'Serbian Dinar',
        'code'                => 941,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'РСД',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'RUB' => [
        'name'                => 'Russian Ruble',
        'code'                => 643,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₽',
        'symbol_first'        => false,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'RWF' => [
        'name'                => 'Rwanda Franc',
        'code'                => 646,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'FRw',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'SAR' => [
        'name'                => 'Saudi Riyal',
        'code'                => 682,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'ر.س',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'SBD' => [
        'name'                => 'Solomon Islands Dollar',
        'code'                => 90,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'SCR' => [
        'name'                => 'Seychelles Rupee',
        'code'                => 690,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₨',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'SDG' => [
        'name'                => 'Sudanese Pound',
        'code'                => 938,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '£',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'SEK' => [
        'name'                => 'Swedish Krona',
        'code'                => 752,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'kr',
        'symbol_first'        => false,
        'decimal_mark'        => ',',
        'thousands_separator' => ' ',
    ],

    'SGD' => [
        'name'                => 'Singapore Dollar',
        'code'                => 702,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'SHP' => [
        'name'                => 'Saint Helena Pound',
        'code'                => 654,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '£',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'SLL' => [
        'name'                => 'Leone',
        'code'                => 694,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Le',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'SOS' => [
        'name'                => 'Somali Shilling',
        'code'                => 706,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Sh',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'SRD' => [
        'name'                => 'Surinam Dollar',
        'code'                => 968,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'SSP' => [
        'name'                => 'South Sudanese Pound',
        'code'                => 728,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '£',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'STD' => [
        'name'                => 'Dobra',
        'code'                => 678,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Db',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'SVC' => [
        'name'                => 'El Salvador Colon',
        'code'                => 222,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₡',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'SYP' => [
        'name'                => 'Syrian Pound',
        'code'                => 760,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '£S',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'SZL' => [
        'name'                => 'Lilangeni',
        'code'                => 748,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'E',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'THB' => [
        'name'                => 'Baht',
        'code'                => 764,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '฿',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'TJS' => [
        'name'                => 'Somoni',
        'code'                => 972,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'ЅМ',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'TMT' => [
        'name'                => 'Turkmenistan New Manat',
        'code'                => 934,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'T',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'TND' => [
        'name'                => 'Tunisian Dinar',
        'code'                => 788,
        'minorUnit'           => 3,
        'subunit'             => 1000,
        'symbol'              => 'د.ت',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'TOP' => [
        'name'                => 'Pa’anga',
        'code'                => 776,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'T$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'TRY' => [
        'name'                => 'Turkish Lira',
        'code'                => 949,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₺',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'TTD' => [
        'name'                => 'Trinidad and Tobago Dollar',
        'code'                => 780,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'TWD' => [
        'name'                => 'New Taiwan Dollar',
        'code'                => 901,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'TZS' => [
        'name'                => 'Tanzanian Shilling',
        'code'                => 834,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Sh',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'UAH' => [
        'name'                => 'Hryvnia',
        'code'                => 980,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '₴',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'UGX' => [
        'name'                => 'Uganda Shilling',
        'code'                => 800,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'USh',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'USD' => [
        'name'                => 'US Dollar',
        'code'                => 840,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'UYU' => [
        'name'                => 'Peso Uruguayo',
        'code'                => 858,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'UZS' => [
        'name'                => 'Uzbekistan Sum',
        'code'                => 860,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'лв',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    // This currency is no longer used. It will be removed soon.
    'VEF' => [
        'name'                => 'Bolivar',
        'code'                => 937,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Bs F',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'VES' => [
        'name'                => 'Bolívar Soberano',
        'code'                => 928,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Bs S',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'VED' => [
        'name'                => 'Dijital Bolívar',
        'code'                => 926,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'Bs D',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'VND' => [
        'name'                => 'Dong',
        'code'                => 704,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => '₫',
        'symbol_first'        => true,
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],

    'VUV' => [
        'name'                => 'Vatu',
        'code'                => 548,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'Vt',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'WST' => [
        'name'                => 'Tala',
        'code'                => 882,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'T',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'XAF' => [
        'name'                => 'CFA Franc BEAC',
        'code'                => 950,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'Fr',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'XAG' => [
        'name'                => 'Silver',
        'code'                => 961,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'oz t',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'XAU' => [
        'name'                => 'Gold',
        'code'                => 959,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'oz t',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'XCD' => [
        'name'                => 'East Caribbean Dollar',
        'code'                => 951,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'XDR' => [
        'name'                => 'SDR (Special Drawing Right)',
        'code'                => 960,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'SDR',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'XOF' => [
        'name'                => 'CFA Franc BCEAO',
        'code'                => 952,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'Fr',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'XPF' => [
        'name'                => 'CFP Franc',
        'code'                => 953,
        'minorUnit'           => 0,
        'subunit'             => 1,
        'symbol'              => 'Fr',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'YER' => [
        'name'                => 'Yemeni Rial',
        'code'                => 886,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '﷼',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'ZAR' => [
        'name'                => 'Rand',
        'code'                => 710,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'R',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'ZMW' => [
        'name'                => 'Zambian Kwacha',
        'code'                => 967,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => 'ZK',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

    'ZWL' => [
        'name'                => 'Zimbabwe Dollar',
        'code'                => 932,
        'minorUnit'           => 2,
        'subunit'             => 100,
        'symbol'              => '$',
        'symbol_first'        => true,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],

];
